services:
  web:
    build: .
    container_name: mixed-navigator-web
    ports:
      - "5000:5000"
    environment:
      OTP_URL: "http://otp:8080/otp/gtfs/v1"
      GTFS_PATH: "/otp-data/moscow-gtfs.zip"
      OTP_FEED_ID: "1"
      NOMINATIM_USER_AGENT: "MixedNavigatorPrototype/0.2"
    volumes:
      - ../data:/otp-data:ro
    restart: unless-stopped
